### ISSUE TITLE
Updating To Latest Version of textgen

### ISSUE THREAD

**Issue by slavakurilyak** [ashleykleynhans/text-generation-docker#2]
How do you update this RunPod template to the latest version of [text-generation-webui](https://github.com/oobabooga/text-generation-webui) by @oobabooga?

Running `./update_linux.sh` encourages me to install [conda](https://github.com/conda/conda) by @conda:

```sh
/update_linux.sh: line 22: /workspace/text-generation-webui/installer_files/conda/etc/profile.d/conda.sh: No such file or directory
./update_linux.sh: line 23: conda: command not found
Conda is not installed. Exiting...
```

**Comment by ashleykleynhans** [comment]
```bash
cd /workspace/text-generation-webui
git checkout main
git pull
```

Then reset your pod.

**Comment by ashleykleynhans** [comment]
The template (version 1.10.1) has also been updated to the latest version.
