### ISSUE TITLE
Kill and restart text generation webui

### ISSUE THREAD

**Issue by alexbrowngh** [ashleykleynhans/text-generation-docker#4]
Hi,

Thanks for providing this wonderful template for runpod. I wonder whether there is a way to kill and restart text generation webui when it hangs without stopping and starting a new instance?

**Comment by ashleykleynhans** [comment]
You can restart it as follows:

```
fuser -k 3001/tcp
cd /workspace/text-generation-webui
nohup ./start_textgen_server.sh > /workspace/logs/textgen.log 2>&1 &
```
